# Generated by Django 5.1.5 on 2025-01-30 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('brightness_score', models.FloatField(blank=True, null=True)),
                ('contrast_score', models.FloatField(blank=True, null=True)),
                ('saturation_score', models.FloatField(blank=True, null=True)),
                ('sharpness_score', models.FloatField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
